authors = ["Kamillo Ferry <kafe@kafe.dev>", "Francesco Nowell", "Benjamin Hollering", "Tobias Boege"]
name = "Maxoids"
uuid = "b7166d23-9f35-4d07-9399-e1add1741ff3"
version = "0.3.0"

[compat]
Oscar = ">=1.6.0"
TikzPictures = "~3.3.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Polymake = "d720cf60-89b5-51f5-aff5-213f193123e7"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[extensions]
TikzExt = ["TikzGraphs", "TikzPictures"]

[extras]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[weakdeps]
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
