name = "Maxoids"
uuid = "b7166d23-9f35-4d07-9399-e1add1741ff3"
authors = ["Kamillo Ferry <kafe@kafe.dev>", "Francesco Nowell", "Benjamin Hollering", "Tobias Boege"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
